# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/teis/git/EdgeCompressor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/teis/git/EdgeCompressor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teis/git/EdgeCompressor/CMakeFiles /home/teis/git/EdgeCompressor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teis/git/EdgeCompressor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compressexec

# Build rule for target.
compressexec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compressexec
.PHONY : compressexec

# fast build rule for target.
compressexec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/build
.PHONY : compressexec/fast

MatLib.o: MatLib.c.o
.PHONY : MatLib.o

# target to build an object file
MatLib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/MatLib.c.o
.PHONY : MatLib.c.o

MatLib.i: MatLib.c.i
.PHONY : MatLib.i

# target to preprocess a source file
MatLib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/MatLib.c.i
.PHONY : MatLib.c.i

MatLib.s: MatLib.c.s
.PHONY : MatLib.s

# target to generate assembly for a file
MatLib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/MatLib.c.s
.PHONY : MatLib.c.s

PMCMean.o: PMCMean.c.o
.PHONY : PMCMean.o

# target to build an object file
PMCMean.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/PMCMean.c.o
.PHONY : PMCMean.c.o

PMCMean.i: PMCMean.c.i
.PHONY : PMCMean.i

# target to preprocess a source file
PMCMean.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/PMCMean.c.i
.PHONY : PMCMean.c.i

PMCMean.s: PMCMean.c.s
.PHONY : PMCMean.s

# target to generate assembly for a file
PMCMean.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/PMCMean.c.s
.PHONY : PMCMean.c.s

bitreader.o: bitreader.c.o
.PHONY : bitreader.o

# target to build an object file
bitreader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/bitreader.c.o
.PHONY : bitreader.c.o

bitreader.i: bitreader.c.i
.PHONY : bitreader.i

# target to preprocess a source file
bitreader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/bitreader.c.i
.PHONY : bitreader.c.i

bitreader.s: bitreader.c.s
.PHONY : bitreader.s

# target to generate assembly for a file
bitreader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/bitreader.c.s
.PHONY : bitreader.c.s

compression.o: compression.c.o
.PHONY : compression.o

# target to build an object file
compression.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/compression.c.o
.PHONY : compression.c.o

compression.i: compression.c.i
.PHONY : compression.i

# target to preprocess a source file
compression.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/compression.c.i
.PHONY : compression.c.i

compression.s: compression.c.s
.PHONY : compression.s

# target to generate assembly for a file
compression.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/compression.c.s
.PHONY : compression.c.s

constants.o: constants.c.o
.PHONY : constants.o

# target to build an object file
constants.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/constants.c.o
.PHONY : constants.c.o

constants.i: constants.c.i
.PHONY : constants.i

# target to preprocess a source file
constants.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/constants.c.i
.PHONY : constants.c.i

constants.s: constants.c.s
.PHONY : constants.s

# target to generate assembly for a file
constants.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/constants.c.s
.PHONY : constants.c.s

error_bound_calculator.o: error_bound_calculator.c.o
.PHONY : error_bound_calculator.o

# target to build an object file
error_bound_calculator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/error_bound_calculator.c.o
.PHONY : error_bound_calculator.c.o

error_bound_calculator.i: error_bound_calculator.c.i
.PHONY : error_bound_calculator.i

# target to preprocess a source file
error_bound_calculator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/error_bound_calculator.c.i
.PHONY : error_bound_calculator.c.i

error_bound_calculator.s: error_bound_calculator.c.s
.PHONY : error_bound_calculator.s

# target to generate assembly for a file
error_bound_calculator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/error_bound_calculator.c.s
.PHONY : error_bound_calculator.c.s

gorilla.o: gorilla.c.o
.PHONY : gorilla.o

# target to build an object file
gorilla.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/gorilla.c.o
.PHONY : gorilla.c.o

gorilla.i: gorilla.c.i
.PHONY : gorilla.i

# target to preprocess a source file
gorilla.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/gorilla.c.i
.PHONY : gorilla.c.i

gorilla.s: gorilla.c.s
.PHONY : gorilla.s

# target to generate assembly for a file
gorilla.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/gorilla.c.s
.PHONY : gorilla.c.s

jsonprint.o: jsonprint.c.o
.PHONY : jsonprint.o

# target to build an object file
jsonprint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/jsonprint.c.o
.PHONY : jsonprint.c.o

jsonprint.i: jsonprint.c.i
.PHONY : jsonprint.i

# target to preprocess a source file
jsonprint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/jsonprint.c.i
.PHONY : jsonprint.c.i

jsonprint.s: jsonprint.c.s
.PHONY : jsonprint.s

# target to generate assembly for a file
jsonprint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/jsonprint.c.s
.PHONY : jsonprint.c.s

mod.o: mod.c.o
.PHONY : mod.o

# target to build an object file
mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/mod.c.o
.PHONY : mod.c.o

mod.i: mod.c.i
.PHONY : mod.i

# target to preprocess a source file
mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/mod.c.i
.PHONY : mod.c.i

mod.s: mod.c.s
.PHONY : mod.s

# target to generate assembly for a file
mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/mod.c.s
.PHONY : mod.c.s

polyswing.o: polyswing.c.o
.PHONY : polyswing.o

# target to build an object file
polyswing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/polyswing.c.o
.PHONY : polyswing.c.o

polyswing.i: polyswing.c.i
.PHONY : polyswing.i

# target to preprocess a source file
polyswing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/polyswing.c.i
.PHONY : polyswing.c.i

polyswing.s: polyswing.c.s
.PHONY : polyswing.s

# target to generate assembly for a file
polyswing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/polyswing.c.s
.PHONY : polyswing.c.s

reader.o: reader.c.o
.PHONY : reader.o

# target to build an object file
reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/reader.c.o
.PHONY : reader.c.o

reader.i: reader.c.i
.PHONY : reader.i

# target to preprocess a source file
reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/reader.c.i
.PHONY : reader.c.i

reader.s: reader.c.s
.PHONY : reader.s

# target to generate assembly for a file
reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/reader.c.s
.PHONY : reader.c.s

swing.o: swing.c.o
.PHONY : swing.o

# target to build an object file
swing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/swing.c.o
.PHONY : swing.c.o

swing.i: swing.c.i
.PHONY : swing.i

# target to preprocess a source file
swing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/swing.c.i
.PHONY : swing.c.i

swing.s: swing.c.s
.PHONY : swing.s

# target to generate assembly for a file
swing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/swing.c.s
.PHONY : swing.c.s

uncompressed_data_maneger.o: uncompressed_data_maneger.c.o
.PHONY : uncompressed_data_maneger.o

# target to build an object file
uncompressed_data_maneger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/uncompressed_data_maneger.c.o
.PHONY : uncompressed_data_maneger.c.o

uncompressed_data_maneger.i: uncompressed_data_maneger.c.i
.PHONY : uncompressed_data_maneger.i

# target to preprocess a source file
uncompressed_data_maneger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/uncompressed_data_maneger.c.i
.PHONY : uncompressed_data_maneger.c.i

uncompressed_data_maneger.s: uncompressed_data_maneger.c.s
.PHONY : uncompressed_data_maneger.s

# target to generate assembly for a file
uncompressed_data_maneger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/uncompressed_data_maneger.c.s
.PHONY : uncompressed_data_maneger.c.s

vector_based.o: vector_based.c.o
.PHONY : vector_based.o

# target to build an object file
vector_based.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/vector_based.c.o
.PHONY : vector_based.c.o

vector_based.i: vector_based.c.i
.PHONY : vector_based.i

# target to preprocess a source file
vector_based.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/vector_based.c.i
.PHONY : vector_based.c.i

vector_based.s: vector_based.c.s
.PHONY : vector_based.s

# target to generate assembly for a file
vector_based.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressexec.dir/build.make CMakeFiles/compressexec.dir/vector_based.c.s
.PHONY : vector_based.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compressexec"
	@echo "... MatLib.o"
	@echo "... MatLib.i"
	@echo "... MatLib.s"
	@echo "... PMCMean.o"
	@echo "... PMCMean.i"
	@echo "... PMCMean.s"
	@echo "... bitreader.o"
	@echo "... bitreader.i"
	@echo "... bitreader.s"
	@echo "... compression.o"
	@echo "... compression.i"
	@echo "... compression.s"
	@echo "... constants.o"
	@echo "... constants.i"
	@echo "... constants.s"
	@echo "... error_bound_calculator.o"
	@echo "... error_bound_calculator.i"
	@echo "... error_bound_calculator.s"
	@echo "... gorilla.o"
	@echo "... gorilla.i"
	@echo "... gorilla.s"
	@echo "... jsonprint.o"
	@echo "... jsonprint.i"
	@echo "... jsonprint.s"
	@echo "... mod.o"
	@echo "... mod.i"
	@echo "... mod.s"
	@echo "... polyswing.o"
	@echo "... polyswing.i"
	@echo "... polyswing.s"
	@echo "... reader.o"
	@echo "... reader.i"
	@echo "... reader.s"
	@echo "... swing.o"
	@echo "... swing.i"
	@echo "... swing.s"
	@echo "... uncompressed_data_maneger.o"
	@echo "... uncompressed_data_maneger.i"
	@echo "... uncompressed_data_maneger.s"
	@echo "... vector_based.o"
	@echo "... vector_based.i"
	@echo "... vector_based.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

